# Generated by Django 3.1.1 on 2021-05-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.FloatField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
    ]
