# Generated by Django 3.1.1 on 2021-05-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210504_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableTrainers',
        ),
    ]
