# Generated by Django 3.1.1 on 2021-06-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTraining',
            fields=[
                ('group_training_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_training_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group_training',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTrainingSchedule',
            fields=[
                ('group_training_schedule_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'group_training_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_up_date', models.DateField()),
                ('is_suspended', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gym_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMemberships',
            fields=[
                ('member_memberships_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'member_memberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_type', models.CharField(max_length=30)),
                ('membership_price', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'membership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('personal_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'personal_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('product_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('receptionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_senior_receptionist', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receptionist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopProducts',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'shop_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_certifications', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trainer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerHours',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trainer_hours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('working_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=5)),
                ('finish_time', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'working_hours',
                'managed': False,
            },
        ),
    ]
