# Generated by Django 3.1.1 on 2021-06-16 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTraining',
            fields=[
                ('group_training_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_training_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_up_date', models.DateField()),
                ('is_suspended', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_type', models.CharField(max_length=30)),
                ('membership_price', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('personal_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('product_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_certifications', models.IntegerField(blank=True, null=True)),
                ('psql', models.CharField(max_length=50)),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.personaldata')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('working_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=5)),
                ('finish_time', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerHours',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gymmember')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.trainer')),
                ('working', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.workinghours')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProducts',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.products')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('receptionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_senior_receptionist', models.BooleanField(blank=True, null=True)),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.personaldata')),
            ],
        ),
        migrations.CreateModel(
            name='MemberMemberships',
            fields=[
                ('member_memberships_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gymmember')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.membership')),
            ],
        ),
        migrations.AddField(
            model_name='gymmember',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.personaldata'),
        ),
        migrations.CreateModel(
            name='GroupTrainingSchedule',
            fields=[
                ('group_training_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_training', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.grouptraining')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.gymmember')),
            ],
        ),
        migrations.AddField(
            model_name='grouptraining',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.trainer'),
        ),
        migrations.AddField(
            model_name='grouptraining',
            name='working',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.workinghours'),
        ),
    ]
