# Generated by Django 3.1.1 on 2021-05-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMemberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('membership_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'active_memberships_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMemberships',
            fields=[
                ('member_memberships_id', models.FloatField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'member_memberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembersHistoryLog',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.gymmember')),
                ('sign_up_date', models.DateField()),
                ('account_susp_date', models.DateField()),
                ('previous_account_state', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members_history_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('personal_data_id', models.FloatField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'personal_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('receptionist_id', models.FloatField(primary_key=True, serialize=False)),
                ('is_senior_receptionist', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receptionist',
                'managed': False,
            },
        ),
    ]
