# Generated by Django 3.1.1 on 2021-06-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grouptraining',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grouptrainingschedule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gymmember',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='membermemberships',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='personaldata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='receptionist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shopproducts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trainerhours',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'managed': False},
        ),
    ]
