# Generated by Django 3.1.1 on 2021-06-16 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20210616_2154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='grouptraining',
            table='group_training',
        ),
        migrations.AlterModelTable(
            name='grouptrainingschedule',
            table='group_training_schedule',
        ),
        migrations.AlterModelTable(
            name='gymmember',
            table='gym_member',
        ),
        migrations.AlterModelTable(
            name='membermemberships',
            table='member_memberships',
        ),
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
        migrations.AlterModelTable(
            name='personaldata',
            table='personal_data',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
        migrations.AlterModelTable(
            name='receptionist',
            table='receptionist',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='shop',
        ),
        migrations.AlterModelTable(
            name='shopproducts',
            table='shop_products',
        ),
        migrations.AlterModelTable(
            name='trainer',
            table='trainer',
        ),
        migrations.AlterModelTable(
            name='trainerhours',
            table='trainer_hours',
        ),
        migrations.AlterModelTable(
            name='workinghours',
            table='working_hours',
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
