DROP TABLE TRAINER_HOURS;
DROP TABLE TRAINER;
DROP TABLE SHOP_PRODUCTS;
DROP TABLE SHOP;
DROP TABLE PRODUCTS;
DROP TABLE WORKING_HOURS;
DROP TABLE MEMBERSHIP;
DROP TABLE GYM_MEMBER;
DROP TABLE ADDRESS;



CREATE TABLE ADDRESS (
    ADDRESS_ID NUMBER,
    POSTCODE VARCHAR2(20 CHAR),
    CITY VARCHAR2(20 CHAR),
    STREET VARCHAR2(20 CHAR),
    CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE TRAINER (
    TRAINER_ID NUMBER,
    FIRST_NAME VARCHAR2(20 CHAR) NOT NULL,
    LAST_NAME VARCHAR2(20 CHAR) NOT NULL,
    ADDRESS_ID NUMBER,
    PHONE_NUMBER VARCHAR2(9 CHAR),
    EMAIL VARCHAR2(30 CHAR) NOT NULL UNIQUE,
    CONSTRAINT TRAINER_PK PRIMARY KEY(TRAINER_ID),
    CONSTRAINT TRAINER_ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE GYM_MEMBER (
    MEMBER_ID NUMBER,
    FIRST_NAME VARCHAR2(20 CHAR) NOT NULL,
    LAST_NAME VARCHAR2(20 CHAR) NOT NULL,
    ADDRESS_ID NUMBER,
    PHONE_NUMBER VARCHAR2(9 CHAR),
    EMAIL VARCHAR2(30 CHAR),
    CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_ID),
    CONSTRAINT MEMBER_ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE MEMBERSHIP (
    MEMBERSHIP_ID NUMBER,
    PURCHASE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    TYPE VARCHAR2(15 CHAR) NOT NULL,
    CONSTRAINT MEMBERSHIP_PK PRIMARY KEY(MEMBERSHIP_ID),
    CONSTRAINT MEMBERSHIP_MEMBER_FK FOREIGN KEY(MEMBER_ID) REFERENCES GYM_MEMBER(MEMBER_ID)
);

CREATE TABLE WORKING_HOURS(
    WORKING_ID NUMBER,
    START_TIME VARCHAR2(5 CHAR),
    FINISH_TIME VARCHAR2(5 CHAR),
    CONSTRAINT WORKING_PK PRIMARY KEY(WORKING_ID)
);

CREATE TABLE TRAINER_HOURS (
    SHIFT_ID NUMBER,
    TRAINER_ID NUMBER,
    WORKING_ID NUMBER,
    MEMBER_ID NUMBER,
    IS_ACTIVE NUMBER(1),
    IS_TAKEN NUMBER(1),
    CONSTRAINT SHIFT_PK PRIMARY KEY(SHIFT_ID),
    CONSTRAINT TRAINER_HOURS_FK FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER(TRAINER_ID),
    CONSTRAINT WORKING_HOURS_FK FOREIGN KEY (WORKING_ID) REFERENCES WORKING_HOURS(WORKING_ID),
    CONSTRAINT MEMBER_HOURS_FK FOREIGN KEY (MEMBER_ID) REFERENCES GYM_MEMBER(MEMBER_ID),
    CONSTRAINT IS_ACTIVE CHECK ( IS_ACTIVE IN (0,1)),
    CONSTRAINT IS_TAKEN CHECK ( IS_TAKEN IN (0,1))
);

CREATE TABLE SHOP (
    SHOP_ID NUMBER,
    NAME VARCHAR2(20 CHAR) NOT NULL,
    ADDRESS_ID NUMBER,
    CONSTRAINT SHOP_PK PRIMARY KEY(SHOP_ID),
    CONSTRAINT SHOP_ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE PRODUCTS(
    PRODUCT_ID NUMBER,
    PRICE NUMBER NOT NULL,
    NAME VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT PRODUCT_PK PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE SHOP_PRODUCTS (
    LISTING_ID NUMBER,
    SHOP_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    CONSTRAINT LISTING_PK PRIMARY KEY(LISTING_ID),
    CONSTRAINT SHOP_LIST_FK FOREIGN KEY(SHOP_ID) REFERENCES SHOP(SHOP_ID),
    CONSTRAINT PRODUCT_LIST FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

